### PR TITLE
Update README to fix latlng order

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR updates the README to adjust the coordinate order in the example urls. After setting this project up, I encountered an error when using the prior example urls.

## Testing
- get and run the container, then try out the prior example endpoints and confirm that the response includes an error noting that the point is outside the watershed
- try the updated example endpoints and verify that it returns results

### CODE REVIEW

**Comment by kellyi** [comment]
I didn't attempt to change this here, but I'm running this using Docker for Mac rather than Docker Machine and the app works using `http://localhost:5000/rwd/39.9408/-75.39926` without having to get the IP address.

**Comment by kellyi** [comment]
Thanks. I pushed another commit which adds Docker for Mac to the existing Linux API endpoint line and specifies that the find-IP instructions are for Docker Machine on macOS.

**Comment by kdeloach** [comment]
👍

**Comment by kellyi** [comment]
Thanks for taking a look!

**Pull request merged**
