### PR TITLE
NHDplus RWD code

### PR DESCRIPTION
**Pull request by pkdash**
Ready for review.

### CODE REVIEW

**Comment by kdeloach** [comment]
Could you provide the arguments necessary to execute this? Specifically, what files do we need for `gage_watershed_shapefile` and `gage_watershed_raster`? Thanks.

**Comment by kdeloach** [comment]
Here are the arguments I tried, which results in an error.

```
root@e55a69c660dd:/opt/rwd/rwd_nhd# python NHD_Rapid_Watershed_Delineation.py 1 1 1 10000 /opt/rwd-data gw id.txt 1 /opt/taudem /usr/local/bin /tmp/test
ERROR 4: `/opt/rwd-data/Main_Watershed/id.txt' not recognised as a supported file format.

Traceback (most recent call last):
  File "NHD_Rapid_Watershed_Delineation.py", line 187, in <module>
    Point_Watershed_Function(*sys.argv[1:])
  File "NHD_Rapid_Watershed_Delineation.py", line 53, in Point_Watershed_Function
    fg = int(extract_value_from_raster_point(gage_watershed_rasterfile, longitude, latitude))
  File "/opt/rwd/rwd_nhd/NHD_RWD_Utilities.py", line 102, in extract_value_from_raster_point
    gt = src_ds.GetGeoTransform()
AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'
```

I'm using the NHD Region 2 data (according to #34) and TauDEM 5.3.7.

For reference, the contents of `Main_Watershed` folder:

```
root@e55a69c660dd:/opt/rwd/rwd_nhd# ll /opt/rwd-data/Main_Watershed
total 3008512
drwxr-xr-x 1 root root    131072 Oct 26 15:27 ./
drwxr-xr-x 1 root root    131072 Oct 26 15:57 ../
-rwxr-xr-x 1 root root 415227417 Oct 26 15:27 ad8.tif*
-rwxr-xr-x 1 root root 905606673 Oct 26 15:27 dist.tif*
-rwxr-xr-x 1 root root  94475574 Oct 26 15:27 fdr.tif*
-rwxr-xr-x 1 root root 111304429 Oct 26 15:27 gord.tif*
-rwxr-xr-x 1 root root         5 Oct 26 15:27 gw.cpg*
-rwxr-xr-x 1 root root     53493 Oct 26 15:27 gw.dbf*
-rwxr-xr-x 1 root root       574 Oct 26 15:27 gw.prj*
-rwxr-xr-x 1 root root     51124 Oct 26 15:27 gw.sbn*
-rwxr-xr-x 1 root root      4084 Oct 26 15:27 gw.sbx*
-rwxr-xr-x 1 root root  75337556 Oct 26 15:27 gw.shp*
-rwxr-xr-x 1 root root      5966 Oct 26 15:27 gw.shp.xml*
-rwxr-xr-x 1 root root     38956 Oct 26 15:27 gw.shx*
-rwxr-xr-x 1 root root 223232129 Oct 26 15:27 gw.tif*
-rwxr-xr-x 1 root root     50346 Oct 26 15:27 id.txt*
-rwxr-xr-x 1 root root 551735363 Oct 26 15:27 plen.tif*
-rwxr-xr-x 1 root root  52787832 Oct 26 15:27 src.tif*
-rwxr-xr-x 1 root root 649080552 Oct 26 15:27 tlen.tif*
```

**Comment by kdeloach** [comment]
For additional context, the original RWD code used the following arguments:

Argument | File
--- | ---
`gage_watershed_file` | delaware_gw_5000_diss
`gage_watershed_ID_file` | Delaware_5000_GW_ID.txt

Source: https://github.com/WikiWatershed/rapid-watershed-delineation/blob/develop/src/api/main.py#L60

It looks like the arguments are a little different for this code. Here are the values I tried, which resulted in the error above:

Argument | File
--- | ---
`gage_watershed_raster` | gw
`gage_watershed_shapefile` | id.txt

**Comment by pkdash** [comment]
For argument  ```gage_watershed_raster``` the file should be ```gw.tif```, and for ```gage_watershed_shapefile``` the file is ```gw```. Try with that and let me know.

**Comment by kdeloach** [comment]
Thanks. 

Here's the result now:

```
root@e55a69c660dd:/opt/rwd/rwd_nhd# python NHD_Rapid_Watershed_Delineation.py 1 1 1 10000 /opt/rwd-data gw gw.tif 1 /opt/taudem /usr/local/bin /tmp/test
ERROR 5: /opt/rwd-data/Main_Watershed/gw.tif, band 1: Access window out of range in RasterIO().  Requested
(-40689,91535) of size 1x1 on raster of 28527x38520.
Traceback (most recent call last):
  File "NHD_Rapid_Watershed_Delineation.py", line 184, in <module>
    Point_Watershed_Function(*sys.argv[1:])
  File "NHD_Rapid_Watershed_Delineation.py", line 50, in Point_Watershed_Function
    fg = int(extract_value_from_raster_point(gage_watershed_rasterfile, longitude, latitude))
  File "/opt/rwd/rwd_nhd/NHD_RWD_Utilities.py", line 111, in extract_value_from_raster_point
    pixel_val = pixel_data[0, 0]    # use the 'short' format code (2 bytes) not int (4 bytes)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pkdash** [comment]
The parameter values seem got switched. Need to pass ```gw.tif``` followed by ```gw```

```python NHD_Rapid_Watershed_Delineation.py 1 1 1 10000 /opt/rwd-data gw.tif gw 1 /opt/taudem /usr/local/bin /tmp/test```

**Comment by kdeloach** [comment]
I have been making minor modifications to this code on my local copy to integrate this into MMW.

However, to keep things simple, I have reverted most of my changes. Here is the exact code I am executing now: https://github.com/kdeloach/rapid-watershed-delineation/commits/nhdplus

Reverting all of my changes and using the arguments you suggested still yield the same error:

```
root@e55a69c660dd:/opt/rwd/rwd-nhd# python NHD_Rapid_Watershed_Delineation.py 1 1 1 10000 /opt/rwd-data gw.tif gw 1 /opt/taudem /usr/local/bin /tmp/test
ERROR 5: /opt/rwd-data/Main_Watershed/gw.tif, band 1: Access window out of range in RasterIO().  Requested
(-40689,91535) of size 1x1 on raster of 28527x38520.
Traceback (most recent call last):
  File "NHD_Rapid_Watershed_Delineation.py", line 174, in <module>
    main(*sys.argv[1:])
  File "NHD_Rapid_Watershed_Delineation.py", line 40, in main
    fg = int(extract_value_from_raster_point(gage_watershed_rasterfile, longitude, latitude))
  File "/opt/rwd/rwd-nhd/NHD_RWD_Utilities.py", line 111, in extract_value_from_raster_point
    pixel_val = pixel_data[0, 0]    # use the 'short' format code (2 bytes) not int (4 bytes)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Are you able to obtain valid results using the same arguments when you run this code locally?

**Comment by dtarb** [comment]
I'm discussing this with Pabitra now.  We think that 1, 1, is not a valid latitude and longitude to input.  Firstly this is a location in the middle of the Atlantic.  Second the RWD code is written using NHDPlus coordinate system which is an Albers projection, not latitude and longitude.  Once lat and long are captured from a click they need to be converted to this Albers projection to use with this function.

In our testing we did test with points outside the domain and found that the error "POINT LOCATED OUTSIDE THE WATERSHED!" was returned from line 45 of the function.  We do not know why your code is not getting to that point.

**Comment by kdeloach** [comment]
I use 1/1 for lat/lng as a sanity check. The original RWD code is able to detect that this point is located outside of the watershed and throws the correct error message:

```
root@08f67ea9fcd6:/opt/rwd/rwd# python Rapid_Watershed_Delineation.py 1 1 1 10000 /opt/rwd-data Delaware_Ocean_stream_dissolve delaware_gw_5000_diss Delaware_5000_GW_ID.txt Delaware_Missing_Coast_Watershed 1 /opt/taudem /usr/local/bin /tmp/test
None
Traceback (most recent call last):
  File "Rapid_Watershed_Delineation.py", line 242, in <module>
    Point_Watershed_Function(*sys.argv[1:])
  File "Rapid_Watershed_Delineation.py", line 65, in Point_Watershed_Function
    raise Exception('Point located outside the watershed.')
Exception: Point located outside the watershed.
```

I tried a few Albers projected coordinates with the rwd-nhd code but received the same error.

Would you mind sending the coordinates that worked for you? Even better, could you send the exact command used in your testing so that I can verify the results match? Thanks.

**Comment by pkdash** [comment]
This command works for me:
```C:\Python-27-x64\python E:\Code\rapid-watershed-delineation\rwd-nhd\NHD_Rapid_Watershed_Delineation.py 1495888.309  2316777.085 1 10000 E:\Pabitra_Work gw.tif gw 1 "C:\Program Files\TauDEM\TauDEM5Exe" "C:\Program Files\Microsoft MPI\Bin"```

This one gives me the error message: POINT LOCATED OUTSIDE THE WATERSHED!

```C:\Python-27-x64\python E:\Code\rapid-watershed-delineation\rwd-nhd\NHD_Rapid_Watershed_Delineation.py 1500124.763  2325647.593 1 10000 E:\Pabitra_Work gw.tif gw 1 "C:\Program Files\TauDEM\TauDEM5Exe" "C:\Program Files\Microsoft MPI\Bin"```

This one gives the error that you are getting:

```C:\Python-27-x64\python E:\Code\rapid-watershed-delineation\rwd-nhd\NHD_Rapid_Watershed_Delineation.py 1 1 1 10000 E:\Pabitra_Work gw.tif gw 8 "C:\Program Files\TauDEM\TauDEM5Exe" "C:\Program Files\Microsoft MPI\Bin"```

**Comment by kdeloach** [comment]
The second command works exactly as expected! However, the first command returns a different error:

```
root@3273c6288a08:/opt/rwd/rwd-nhd# python NHD_Rapid_Watershed_Delineation.py 1495888.309 2316777.085 1 10000 /opt/rwd-data gw.tif gw 1 /opt/taudem /usr/local/bin /tmp/test
1918
search 0.012491941452 seconds ---
Traceback (most recent call last):
  File "NHD_Rapid_Watershed_Delineation.py", line 174, in <module>
    main(*sys.argv[1:])
  File "NHD_Rapid_Watershed_Delineation.py", line 78, in main
    distance_thresh))
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

It looks like it fails when trying to run this command:

> "mpiexec"  "-n"  "1"  "moveoutletstostreams"  "-p"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif"  "-src"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif"  "-o"  "/tmp/test/mypoint.shp"  "-om"  "/tmp/test/New_Outlet.shp"  "-md"  "10000.0"

When I run this command manually I get the following error:

```
root@3273c6288a08:/opt/rwd/rwd-nhd#  "mpiexec"  "-n"  "1"  "moveoutletstostreams"  "-p"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif"  "-src"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif"  "-o"  "/tmp/test/mypoint.shp"  "-om"  "/tmp/test/New_Outlet.shp"  "-md"  "10000.0"
--------------------------------------------------------------------------
mpiexec was unable to find the specified executable file, and therefore
did not launch the job.  This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpiexec command
      line parameter option (remember that mpiexec interprets the first
      unrecognized command line token as the executable).

Node:       3273c6288a08
Executable: moveoutletstostreams
--------------------------------------------------------------------------
```

**Comment by kdeloach** [comment]
Does the `moveoutletstostreams` command exist in TauDEM 5.3.7? I found another command with a slightly different spelling: `moveoutletstostrm`

**Comment by kdeloach** [comment]
After adding some bug fixes taken from the old version of RWD (https://github.com/kdeloach/rapid-watershed-delineation/commit/d2ebed5c324a1b14bfee9901aa575e8561926acf) I was able to generate a command which executes inside our Docker container, but now it produces this error:

```
root@3273c6288a08:/opt/rwd/rwd-nhd# "/usr/local/bin/mpiexec"  "--allow-run-as-root"  "-np"  "1"  "/opt/taudem/moveoutletstostrm"  "-p"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif"  "-src"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif"  "-o"  "/tmp/test/mypoint.shp"  "-om"  "/tmp/test/New_Outlet.shp"  "-md"  "10000.0"
MoveOutletsToStreams version 5.3.7
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif has projected coordinate system.
ERROR 1: /tmp/test/New_Outlet.shp is not a directory.

ERROR 10: Pointer 'hDS' is NULL in 'OGR_DS_Destroy'.

Total time: 0.012589
```

For reference, here are the contents of the output directory:

```
root@3273c6288a08:/opt/rwd/rwd-nhd# ll /tmp/test/
total 44
drwxr-xr-x 2 root root 4096 Oct 26 20:36 ./
drwxrwxrwt 3 root root 4096 Oct 26 20:39 ../
-rw-r--r-- 1 root root  226 Oct 26 20:30 New_Outlet.dbf
-rw-r--r-- 1 root root  576 Oct 26 20:30 New_Outlet.prj
-rw-r--r-- 1 root root  128 Oct 26 20:30 New_Outlet.shp
-rw-r--r-- 1 root root  108 Oct 26 20:30 New_Outlet.shx
-rw-r--r-- 1 root root   10 Oct 26 20:36 mypoint.cpg
-rw-r--r-- 1 root root  188 Oct 26 20:36 mypoint.dbf
-rw-r--r-- 1 root root  423 Oct 26 20:36 mypoint.prj
-rw-r--r-- 1 root root  128 Oct 26 20:36 mypoint.shp
-rw-r--r-- 1 root root  108 Oct 26 20:36 mypoint.shx
```

**Comment by pkdash** [comment]
The ```moveoutletstostreams``` is the correct command name in TauDEM 5.3.7

**Comment by kdeloach** [comment]
I see. Maybe there is a difference in how we install TauDEM in our environment which results in a difference in the name of this command. In any case, it still produces an error.

 The error message (`ERROR 1: /tmp/test/New_Outlet.shp is not a directory`) leads me to believe that one of the arguments is incorrect. However, I'm not sure how that's possible, since the same command arguments work for you.

As for dependencies, we are using:

* TauDEM 5.3.7
* MPI 1.8.1
* GDAL 1.11.0

Source https://github.com/kdeloach/docker-rwd/blob/e2e579e934665e77b41f284591934832d64911d1/Dockerfile#L5

**Comment by dtarb** [comment]
Yes the makefile on linux uses the name that you are using so there are PC vs Linux differences.

**Comment by dtarb** [comment]
We could insert debugging code to figure out which of the OGR open calls is failing.

**Comment by dtarb** [comment]
We are suspecting that it is an OGR datasource vs data layer issue that we do not fully understand and may be different between linux and PC.  I think the earlier code that Nazmus had that you used for Delaware did not use OGR fully.  Could you try writing the new shapefile to a different directory that is empty and does not have a shapefile in it already.  OGR has a model for data sources as folders that I do not understand fully that may be causing the issue.

**Comment by dtarb** [comment]
Can you try the function with arguments 
-om /tmp/test/ -omlyr New_outlet.shp

This separates the datasource as the folder and layer as the shapefile.

The full command would be

"/usr/local/bin/mpiexec"  "--allow-run-as-root"  "-np"  "1"  "/opt/taudem/moveoutletstostrm"  "-p"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif"  "-src"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif"  "-o"  "/tmp/test/mypoint.shp"  "-om"  "/tmp/test/" "-omlyr" "New_Outlet.shp" "-md"  "10000.0"

**Comment by kdeloach** [comment]
Thanks, that makes sense. 

After clearing out my test folder and making a few [minor tweaks](https://github.com/kdeloach/rapid-watershed-delineation/commit/ebb626c981fd3204bf4e33c3b29cb649aa51802f) I got the following results:

```
root@3273c6288a08:/opt/rwd/rwd-nhd# python NHD_Rapid_Watershed_Delineation.py 1495888.309 2316777.085 1 10000 /opt/rwd-data gw.tif gw 1 /opt/taudem /usr/local/bin /tmp/test
1918
search 0.0124289989471 seconds ---
"/usr/local/bin/mpiexec"  "--allow-run-as-root"  "-np"  "1"  "/opt/taudem/moveoutletstostrm"  "-p"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif"  "-src"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif"  "-o"  "/tmp/test/mypoint.shp"  "-om"  "/tmp/test/New_Outlet.shp"  "-md"  "10000.0" 
MoveOutletsToStreams version 5.3.7
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif has projected coordinate system.
New_Outlet Total time: 0.013512
Gage Watershed version 5.3.7
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Size: 1
Read time: 0.009625
Compute time: 0.047767
Write time: 0.015353
Total time: 0.072745
Creating output local_subwatershed.shp of format ESRI Shapefile.
0...10...20...30...40...50...60...70...80...90...100 - done.
ogr2ogr local_subwatershed_dissolve.shp local_subwatershed.shp -dialect sqlite -sql  "SELECT GRIDCODE , ST_Union(geometry) as geometry FROM   'local_subwatershed'   GROUP BY GRIDCODE"   -nln results -overwrite
Identify upstream watershed 6.00139212608 seconds ---
Up stream edge was reached
ogr2ogr -update -append /tmp/test/local_subwatershed_dissolve.shp /opt/rwd-data/Subwatershed_ALL/Subwatershed1948/Full_watershed1948.shp
sh: 1: Syntax error: Unterminated quoted string
Traceback (most recent call last):
  File "NHD_Rapid_Watershed_Delineation.py", line 175, in <module>
    main(*sys.argv[1:])
  File "NHD_Rapid_Watershed_Delineation.py", line 163, in main
    subwatershed_dir, output_dir)
  File "/opt/rwd/rwd-nhd/NHD_RWD_Utilities.py", line 199, in get_watershed_attributes
    layer = source.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'
```

**Comment by kdeloach** [comment]
Do we also need to update GDAL and MPI for this to work? I noticed there were some dependency changes here: https://github.com/dtarb/TauDEM/commit/614984b9b7c80322bc860f759e7dd14a3e045a8f

Upgrading GDAL shouldn't be a problem but I think we'll have to stick with Open MPI since we are building this in a Linux environment.

**Comment by dtarb** [comment]
I do not think this is dependency related.  We have not done anything different with MPI for a long time so Open MPI should be fine.  GDAL we are using OGR for shape IO.  Previously we used shapelib.  I think the issue may be related to this, but more likely a bug/type mismatch than a dependency issue.

**Comment by dtarb** [comment]
Do you want to get on the phone to talk this through.  435 797 3172

**Comment by kdeloach** [comment]
Are you available to discuss tomorrow? Which time works best for you?

**Comment by dtarb** [comment]
Tomorrow is better.  Any time before 11 am mountain time.  Preferably after 8:30 mountain time (10:30 ET)

**Comment by dtarb** [comment]
I have class 11:30 to 1, but could meet after that (2 pm MT = 4 pm ET)

**Comment by kdeloach** [comment]
I was able to fix the syntax error in the command above (See https://github.com/WikiWatershed/rapid-watershed-delineation/pull/36/commits/da11677674c6284495842aa59545cd73413c3432) and now it looks like everything is working!

```
root@3273c6288a08:/opt/rwd/rwd-nhd# python NHD_Rapid_Watershed_Delineation.py 1495888.309 2316777.085 1 10000 /opt/rwd-data gw.tif gw 1 /opt/taudem /usr/local/bin /tmp/test1918
search 0.0156350135803 seconds ---
"/usr/local/bin/mpiexec"  "--allow-run-as-root"  "-np"  "1"  "/opt/taudem/moveoutletstostrm"  "-p"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif"  "-src"  "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif"  "-o"  "/tmp/test/mypoint.shp"  "-om"  "/tmp/test/New_Outlet.shp"  "-md"  "10000.0"
MoveOutletsToStreams version 5.3.7
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918src1.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif has projected coordinate system.
New_Outlet Total time: 0.013227
"/usr/local/bin/mpiexec" "--allow-run-as-root" "-np" "1" "/opt/taudem/gagewatershed" "-p" "/opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif" "-o" "/tmp/test/New_Outlet.shp" "-gw" "/tmp/test/local_subwatershed.tif" "-id" "/tmp/test/local_subwatershed.txt" "-upid" "/tmp/test/upwacoor.txt"
Gage Watershed version 5.3.7
Input file /opt/rwd-data/Subwatershed_ALL/Subwatershed1918/subwatershed_1918p.tif has projected coordinate system.
This run may take on the order of 1 minutes to complete.
This estimate is very approximate.
Run time is highly uncertain as it depends on the complexity of the input data
and speed and memory of the computer. This estimate is based on our testing on
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Size: 1
Read time: 0.009545
Compute time: 0.048271
Write time: 0.015123
Total time: 0.072939
gdal_polygonize.py -8 local_subwatershed.tif -b 1 -f "ESRI Shapefile"  local_subwatershed.shp local_subwatershed GRIDCODE
Creating output local_subwatershed.shp of format ESRI Shapefile.
0...10...20...30...40...50...60...70...80...90...100 - done.
ogr2ogr local_subwatershed_dissolve.shp local_subwatershed.shp -dialect sqlite -sql  "SELECT GRIDCODE , ST_Union(geometry) as geometry FROM   'local_subwatershed'   GROUP BY GRIDCODE"   -nln results -overwrite
Identify upstream watershed 0.203817129135 seconds ---
Up stream edge was reached
ogr2ogr -update -append /tmp/test/local_subwatershed_dissolve.shp /opt/rwd-data/Subwatershed_ALL/Subwatershed1948/Full_watershed1948.shp
ogr2ogr New_Point_Watershed.shp local_subwatershed_dissolve.shp -dialect sqlite -sql  "SELECT GRIDCODE , ST_Union(geometry) as geometry FROM local_subwatershed_dissolve"
writing  time 0.000164985656738 seconds ---
watershed attributes time 0.321979045868 seconds ---
```

**Comment by pkdash** [comment]
@kdeloach Great.

**Comment by kdeloach** [comment]
I believe this can be merged now.

**Pull request merged**
